service: express-app

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2

functions:
  app:
    handler: app.handler
    events:
      - httpApi: # Uses HTTP API Gateway
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline # Optional, for local testing

custom:
  serverless-offline:
    httpPort: 3000
